services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      - shared_network

networks:
  shared_network:
    external: true

